---
#- include: osp-provision.yml

- name: Gather facts
  gather_facts: false
  hosts: jumpbox
  become: false
  roles:
  - osp-facts
  tasks:
  - name: Wait for instances to be available
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: "{{ inventory_hostname }}"
    with_items:
      "{{ groups.all }}"

- include: app-deploy.yml GUID=d094
